// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// neighbor_overlap_counts
IntegerMatrix neighbor_overlap_counts(const NumericMatrix& idx, const NumericMatrix& ref_idx, const IntegerVector& k, double n_threads);
RcppExport SEXP _quadra_neighbor_overlap_counts(SEXP idxSEXP, SEXP ref_idxSEXP, SEXP kSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type ref_idx(ref_idxSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(neighbor_overlap_counts(idx, ref_idx, k, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// random_distances
List random_distances(NumericMatrix xin, NumericMatrix xout, const std::string& metric_in, const std::string& metric_out, double n_pairs, double n_threads, Nullable<IntegerMatrix> pairs, bool ret_pairs);
RcppExport SEXP _quadra_random_distances(SEXP xinSEXP, SEXP xoutSEXP, SEXP metric_inSEXP, SEXP metric_outSEXP, SEXP n_pairsSEXP, SEXP n_threadsSEXP, SEXP pairsSEXP, SEXP ret_pairsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type xin(xinSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type xout(xoutSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type metric_in(metric_inSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type metric_out(metric_outSEXP);
    Rcpp::traits::input_parameter< double >::type n_pairs(n_pairsSEXP);
    Rcpp::traits::input_parameter< double >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerMatrix> >::type pairs(pairsSEXP);
    Rcpp::traits::input_parameter< bool >::type ret_pairs(ret_pairsSEXP);
    rcpp_result_gen = Rcpp::wrap(random_distances(xin, xout, metric_in, metric_out, n_pairs, n_threads, pairs, ret_pairs));
    return rcpp_result_gen;
END_RCPP
}
// rnx_auc_direct
double rnx_auc_direct(const NumericMatrix& din, const NumericMatrix& dout);
RcppExport SEXP _quadra_rnx_auc_direct(SEXP dinSEXP, SEXP doutSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type din(dinSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type dout(doutSEXP);
    rcpp_result_gen = Rcpp::wrap(rnx_auc_direct(din, dout));
    return rcpp_result_gen;
END_RCPP
}
// rnx_curve_direct
NumericVector rnx_curve_direct(const NumericMatrix& din, const NumericMatrix& dout, const IntegerVector& k);
RcppExport SEXP _quadra_rnx_curve_direct(SEXP dinSEXP, SEXP doutSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type din(dinSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type dout(doutSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(rnx_curve_direct(din, dout, k));
    return rcpp_result_gen;
END_RCPP
}
// trustworthiness_exact
double trustworthiness_exact(const NumericMatrix& din, const NumericMatrix& dout, int k);
RcppExport SEXP _quadra_trustworthiness_exact(SEXP dinSEXP, SEXP doutSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type din(dinSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type dout(doutSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(trustworthiness_exact(din, dout, k));
    return rcpp_result_gen;
END_RCPP
}
// continuity_exact
double continuity_exact(const NumericMatrix& din, const NumericMatrix& dout, int k);
RcppExport SEXP _quadra_continuity_exact(SEXP dinSEXP, SEXP doutSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type din(dinSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type dout(doutSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(continuity_exact(din, dout, k));
    return rcpp_result_gen;
END_RCPP
}
// trustworthiness_exact_multi
NumericVector trustworthiness_exact_multi(const NumericMatrix& din, const NumericMatrix& dout, const IntegerVector& k);
RcppExport SEXP _quadra_trustworthiness_exact_multi(SEXP dinSEXP, SEXP doutSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type din(dinSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type dout(doutSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(trustworthiness_exact_multi(din, dout, k));
    return rcpp_result_gen;
END_RCPP
}
// continuity_exact_multi
NumericVector continuity_exact_multi(const NumericMatrix& din, const NumericMatrix& dout, const IntegerVector& k);
RcppExport SEXP _quadra_continuity_exact_multi(SEXP dinSEXP, SEXP doutSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type din(dinSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type dout(doutSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(continuity_exact_multi(din, dout, k));
    return rcpp_result_gen;
END_RCPP
}
// triplet_sample
double triplet_sample(const NumericMatrix& triplets, const NumericMatrix& xin, const NumericMatrix& xout, const std::string& metric_in, const std::string& metric_out, double n_threads);
RcppExport SEXP _quadra_triplet_sample(SEXP tripletsSEXP, SEXP xinSEXP, SEXP xoutSEXP, SEXP metric_inSEXP, SEXP metric_outSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type triplets(tripletsSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type xin(xinSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type xout(xoutSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type metric_in(metric_inSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type metric_out(metric_outSEXP);
    Rcpp::traits::input_parameter< double >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(triplet_sample(triplets, xin, xout, metric_in, metric_out, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// triplet_plan_sample
SEXP triplet_plan_sample(const IntegerMatrix& triplets, const NumericMatrix& xin, const NumericMatrix& xout, const std::string& metric_in, const std::string& metric_out, double n_threads, bool ret_triplets);
RcppExport SEXP _quadra_triplet_plan_sample(SEXP tripletsSEXP, SEXP xinSEXP, SEXP xoutSEXP, SEXP metric_inSEXP, SEXP metric_outSEXP, SEXP n_threadsSEXP, SEXP ret_tripletsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type triplets(tripletsSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type xin(xinSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type xout(xoutSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type metric_in(metric_inSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type metric_out(metric_outSEXP);
    Rcpp::traits::input_parameter< double >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type ret_triplets(ret_tripletsSEXP);
    rcpp_result_gen = Rcpp::wrap(triplet_plan_sample(triplets, xin, xout, metric_in, metric_out, n_threads, ret_triplets));
    return rcpp_result_gen;
END_RCPP
}
// random_triplet_sample
SEXP random_triplet_sample(const NumericMatrix& xin, const NumericMatrix& xout, double n_triplets, const std::string& metric_in, const std::string& metric_out, double n_threads, bool ret_triplets);
RcppExport SEXP _quadra_random_triplet_sample(SEXP xinSEXP, SEXP xoutSEXP, SEXP n_tripletsSEXP, SEXP metric_inSEXP, SEXP metric_outSEXP, SEXP n_threadsSEXP, SEXP ret_tripletsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type xin(xinSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type xout(xoutSEXP);
    Rcpp::traits::input_parameter< double >::type n_triplets(n_tripletsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type metric_in(metric_inSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type metric_out(metric_outSEXP);
    Rcpp::traits::input_parameter< double >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type ret_triplets(ret_tripletsSEXP);
    rcpp_result_gen = Rcpp::wrap(random_triplet_sample(xin, xout, n_triplets, metric_in, metric_out, n_threads, ret_triplets));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_quadra_neighbor_overlap_counts", (DL_FUNC) &_quadra_neighbor_overlap_counts, 4},
    {"_quadra_random_distances", (DL_FUNC) &_quadra_random_distances, 8},
    {"_quadra_rnx_auc_direct", (DL_FUNC) &_quadra_rnx_auc_direct, 2},
    {"_quadra_rnx_curve_direct", (DL_FUNC) &_quadra_rnx_curve_direct, 3},
    {"_quadra_trustworthiness_exact", (DL_FUNC) &_quadra_trustworthiness_exact, 3},
    {"_quadra_continuity_exact", (DL_FUNC) &_quadra_continuity_exact, 3},
    {"_quadra_trustworthiness_exact_multi", (DL_FUNC) &_quadra_trustworthiness_exact_multi, 3},
    {"_quadra_continuity_exact_multi", (DL_FUNC) &_quadra_continuity_exact_multi, 3},
    {"_quadra_triplet_sample", (DL_FUNC) &_quadra_triplet_sample, 6},
    {"_quadra_triplet_plan_sample", (DL_FUNC) &_quadra_triplet_plan_sample, 7},
    {"_quadra_random_triplet_sample", (DL_FUNC) &_quadra_random_triplet_sample, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_quadra(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
