# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

random_distances <- function(xin, xout, metric_in = "euclidean", metric_out = "euclidean", n_pairs = 10000L, n_threads = 0L, verbose = FALSE) {
    .Call(`_quadra_random_distances`, xin, xout, metric_in, metric_out, n_pairs, n_threads, verbose)
}

triplet_sample <- function(triplets, xin, xout, metric_in = "sqeuclidean", metric_out = "sqeuclidean", n_threads = 0L) {
    .Call(`_quadra_triplet_sample`, triplets, xin, xout, metric_in, metric_out, n_threads)
}

