# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

triplet_sample <- function(triplets, xin, xout, metric_in = "l2sqr", metric_out = "l2sqr", n_threads = 0L, grain_size = 1L) {
    .Call(`_quadra_triplet_sample`, triplets, xin, xout, metric_in, metric_out, n_threads, grain_size)
}

