# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

neighbor_overlap_counts <- function(idx, ref_idx, k, n_threads = 0L) {
    .Call(`_quadra_neighbor_overlap_counts`, idx, ref_idx, k, n_threads)
}

random_distances <- function(xin, xout, metric_in = "euclidean", metric_out = "euclidean", n_pairs = 10000L, n_threads = 0L, verbose = FALSE) {
    .Call(`_quadra_random_distances`, xin, xout, metric_in, metric_out, n_pairs, n_threads, verbose)
}

rnx_auc_direct <- function(din, dout) {
    .Call(`_quadra_rnx_auc_direct`, din, dout)
}

trustworthiness_exact <- function(din, dout, k) {
    .Call(`_quadra_trustworthiness_exact`, din, dout, k)
}

continuity_exact <- function(din, dout, k) {
    .Call(`_quadra_continuity_exact`, din, dout, k)
}

triplet_sample <- function(triplets, xin, xout, metric_in = "sqeuclidean", metric_out = "sqeuclidean", n_threads = 0L) {
    .Call(`_quadra_triplet_sample`, triplets, xin, xout, metric_in, metric_out, n_threads)
}

random_triplet_sample <- function(xin, xout, n_triplets = 5L, metric_in = "sqeuclidean", metric_out = "sqeuclidean", n_threads = 0L) {
    .Call(`_quadra_random_triplet_sample`, xin, xout, n_triplets, metric_in, metric_out, n_threads)
}

